apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: stockapp
    app.kubernetes.io/instance: stockapp-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: stockapp
spec:
  selector:
    app: stockapp
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
